CC=g++
CPPFLAGS="-I/home/trentonknight/Development/OpenGL-Junk1/include/"
LDLIBS = -lXxf86vm -lX11 -lglapi -lglfw3 -lXi -lpthread -lXrandr -lstdc++ -lm -lGLEW -lGLU -lGL -lrt
all: test
clean:
	rm -f *.o 
.PHONY: all clean

